### ISSUE TITLE
Feedback for part 1

### ISSUE THREAD

**Issue by TanSA05** [ryyeh/team4-project#2]
Your business case is clear. I see the raw data is loaded, but it hasn’t been cleaned yet. Roles and responsibilities also aren’t defined, so it’s unclear who’s tackling each part. There’s no exploratory analysis or code documentation available yet, which limits feedback on analysis and clarity. The README is not understandable. (all of this was a requirement for this part of the project)

**Comment by ryyeh** [comment]
Sorry we didn't see this comment until now.

A lot of the work we've been doing hasn't been uploaded to the GitHub repo yet.

Thank you for your feedback!
